variable "project_id" {
  type        = string
  description = "The GCP project ID to deploy resources to."
  default     = "echoloop-500808"
}

variable "region" {
  type        = string
  description = "The GCP region to deploy resources in."
  default     = "europe-west4"
}

variable "google_client_id" {
  type        = string
  description = "The OAuth 2.0 Client ID generated by Google Console."
}

variable "google_client_secret" {
  type        = string
  description = "The OAuth 2.0 Client Secret generated by Google Console."
  sensitive   = true
}

variable "allowed_emails" {
  type        = string
  description = "Comma-separated list of whitelisted Google account emails."
  default     = ""
}

variable "image_tag" {
  type        = string
  description = "The Docker container image tag to deploy."
  default     = "latest"
}
